version: '3.9'
services:
  database:
    image: postgres:13.13-alpine
    container_name: database_Leo
    restart: always
    environment:

      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Leo
      POSTGRES_USER: admin

    volumes:
      -  /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
      
    depends_on:
     - database
